### PR TITLE
fix: os.userInfo() might throw SystemError if homedir isn't available

### LINKED ISSUE #77: 'compute' can throw for user using ldap
Original issue https://github.com/microsoft/vscode-remote-release/issues/9649#issuecomment-2015267838

Here, https://github.com/cyjake/ssh-config/blob/162eaa36ad7a0ffce0a463322e50a1633f9bd478/src/ssh-config.ts#L172C15-L172C26

`os.userInfo` can throw for some users https://nodejs.org/api/os.html#osuserinfooptions

But it looks like `User` is optional here, or may not be needed, what do you think?

### PR DESCRIPTION
**Pull request by cyjake**
fixes #77

### CODE REVIEW

File: src/ssh-config.ts [hunk 1]
```diff
@@ -164,13 +164,21 @@ export default class SSHConfig extends Array<Line> {
   public compute(opts: string | MatchOptions): Record<string, string | string[]> {
     if (typeof opts === 'string') opts = { Host: opts }
 
+    let userInfo: { username: string }
+    try {
+      userInfo = os.userInfo()
+    } catch {
+      // os.userInfo() throws a SystemError if a user has no username or homedir.
```
Comment (mcallaghan-geotab) [inline src/ssh-config.ts:171]: FYI: this comment isn't necessarily precise

namely this can happen as well if the user is a "remote" user (e.g. LDAP scenario)

Comment (cyjake) [reply src/ssh-config.ts:171]: It was copied from the documentation of os.userInfo() 😂 I guess if the user is "remote", homedir won't be available as well?
